version: '3.8'

services:
  ark-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ark-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_PATH=/app/data/ark.db
      - UPLOAD_PATH=/app/uploads
      - ALLOWED_ORIGINS=http://localhost,http://127.0.0.1,http://host.docker.internal
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ark-network

  ark-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ark-frontend
    ports:
      - "80:80"
    environment:
      - NGINX_BACKEND_URL=http://ark-backend:3000
    depends_on:
      - ark-backend
    restart: unless-stopped
    networks:
      - ark-network

networks:
  ark-network:
    driver: bridge

volumes:
  ark-data:
  ark-uploads:
  ark-logs: